# Generated by Django 4.2.30 on 2026-07-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_preferred_location_agentdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdocument',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentdocument',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
