# Generated by Django 4.2.30 on 2026-07-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('field_engineer', 'Field Engineer'), ('builder', 'Builder'), ('buyer', 'Buyer'), ('technical_auditor', 'Technical Auditor')], default='field_engineer', max_length=20),
        ),
    ]
