# Generated by Django 4.2.30 on 2026-07-09 13:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='read',
            new_name='is_read',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='recipient',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('general', 'General'), ('enquiry_created', 'Enquiry Created'), ('agent_assigned', 'Agent Assigned'), ('inspection_started', 'Inspection Started'), ('inspection_completed', 'Inspection Completed'), ('engineer_assigned', 'Engineer Assigned'), ('inspection_approved', 'Inspection Approved'), ('inspection_rejected', 'Inspection Rejected'), ('certificate_generated', 'Certificate Generated')], default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='reference_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='notification',
            table='notifications',
        ),
    ]
