# Generated by Django 4.2.30 on 2026-07-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('general', 'General'), ('enquiry_created', 'Enquiry Created'), ('field_engineer_assigned', 'Field Engineer Assigned'), ('inspection_started', 'Inspection Started'), ('inspection_completed', 'Inspection Completed'), ('technical_auditor_assigned', 'Technical Auditor Assigned'), ('inspection_approved', 'Inspection Approved'), ('inspection_rejected', 'Inspection Rejected'), ('certificate_generated', 'Certificate Generated')], default='general', max_length=50),
        ),
    ]
