# Generated by Django 4.2.30 on 2026-07-02 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='id',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='id',
            new_name='question_id',
        ),
        migrations.RenameField(
            model_name='template',
            old_name='id',
            new_name='template_id',
        ),
        migrations.RenameField(
            model_name='templatecategory',
            old_name='id',
            new_name='template_category_id',
        ),
        migrations.RenameField(
            model_name='templatequestion',
            old_name='id',
            new_name='template_question_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('question_category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_questions', to='questionnaires.category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questioncategory_created_by', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_categories', to='questionnaires.question')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questioncategory_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('question', 'category')},
            },
        ),
    ]
