# Generated by Django 4.2.30 on 2026-07-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0002_rename_id_category_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
