# Generated by Django 4.2.30 on 2026-07-06 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0004_question_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ['name', 'version']},
        ),
        migrations.AlterUniqueTogether(
            name='templatequestion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='templatequestion',
            name='template_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_questions', to='questionnaires.templatecategory'),
        ),
        migrations.AlterUniqueTogether(
            name='template',
            unique_together={('name', 'property_type', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='templatequestion',
            unique_together={('template_category', 'question')},
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['property_type'], name='questionnai_propert_7d94b8_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['is_active'], name='questionnai_is_acti_9d163e_idx'),
        ),
    ]
