# Generated by Django 4.2.30 on 2026-07-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0005_alter_template_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('rating', 'Rating'), ('yes_no', 'Yes No'), ('multiple_choice', 'Multiple Choice'), ('photo', 'Photo'), ('video', 'Video'), ('dropdown', 'Dropdown'), ('checkbox', 'Checkbox')], max_length=30),
        ),
    ]
