# Generated by Django 4.2.30 on 2026-07-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='enquiry_number',
            field=models.CharField(default=1000001, max_length=100),
            preserve_default=False,
        ),
    ]
