# Generated by Django 4.2.30 on 2026-07-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0004_alter_enquiry_enquiry_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_number',
            field=models.CharField(blank=True, default='', editable=False, max_length=20),
        ),
    ]
