# Generated by Django 4.2.30 on 2026-07-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0006_alter_enquiry_enquiry_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('agent_assigned', 'Agent Assigned'), ('engineer_assigned', 'Engineer Assigned'), ('inspection_in_progress', 'Inspection In Progress'), ('inspection_completed', 'Inspection Completed'), ('under_review', 'Under Review'), ('certified', 'Certified'), ('certificate_issued', 'Certificate Issued')], default='pending', max_length=50),
        ),
    ]
