# Generated by Django 4.2.30 on 2026-07-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0007_alter_enquiry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('agent_assigned', 'Field Engineer Assigned'), ('engineer_assigned', 'Technical Auditor Assigned'), ('inspection_in_progress', 'Inspection In Progress'), ('inspection_completed', 'Inspection Completed'), ('under_review', 'Under Review'), ('certified', 'Certified'), ('certificate_issued', 'Certificate Issued')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='enquiryassignment',
            name='role',
            field=models.CharField(choices=[('agent', 'Field Engineer'), ('engineer', 'Technical Auditor')], max_length=20),
        ),
    ]
