# Generated by Django 4.2.30 on 2026-07-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0008_alter_enquiry_status_alter_enquiryassignment_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('field_engineer_assigned', 'Field Engineer Assigned'), ('technical_auditor_assigned', 'Technical Auditor Assigned'), ('inspection_in_progress', 'Inspection In Progress'), ('inspection_completed', 'Inspection Completed'), ('under_review', 'Under Review'), ('certified', 'Certified'), ('certificate_issued', 'Certificate Issued')], default='pending', max_length=50),
        ),
    ]
