# Generated by Django 4.2 on 2026-07-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0009_alter_enquiry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiryassignment',
            name='role',
            field=models.CharField(choices=[('field_engineer', 'Field Engineer'), ('technical_auditor', 'Technical Auditor')], max_length=20),
        ),
    ]
