# Generated by Django 4.2 on 2026-07-29 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0009_itemlibrary'),
        ('enquiries', '0010_alter_enquiryassignment_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='questionnaire_template',
        ),
        migrations.RemoveField(
            model_name='enquiryassignment',
            name='questionnaire_template',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.template'),
        ),
        migrations.AddField(
            model_name='enquiryassignment',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='masters.template'),
        ),
    ]
