# Generated by Django 4.2 on 2026-07-29 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enquiries', '0011_remove_enquiry_questionnaire_template_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0009_itemlibrary'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionItemResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('good', 'Good'), ('minor_issue', 'Minor Issue'), ('major_issue', 'Major Issue'), ('not_applicable', 'Not Applicable')], max_length=30)),
                ('severity', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('observation', models.TextField(blank=True)),
                ('rectification', models.TextField(blank=True)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('inspected_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_started', max_length=30)),
                ('overall_notes', models.TextField(blank=True, default='')),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('obtained_score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('maximum_score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enquiry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='newinspection_report', to='enquiries.enquiry')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='newinspection_reports', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='newinspection_reports', to='masters.template')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], max_length=20)),
                ('file', models.FileField(upload_to='inspection_media/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='inspection.inspectionitemresponse')),
            ],
        ),
        migrations.AddField(
            model_name='inspectionitemresponse',
            name='inspection_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='inspection.inspectionreport'),
        ),
        migrations.AddField(
            model_name='inspectionitemresponse',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='masters.item'),
        ),
        migrations.CreateModel(
            name='InspectionActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='inspection.inspectionreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='inspectionitemresponse',
            unique_together={('inspection_report', 'item')},
        ),
    ]
