# Generated by Django 4.2 on 2026-07-29 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('findings', models.TextField()),
                ('recommendations', models.TextField()),
                ('status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspection_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='inspection.inspectionreport')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InspectionItemReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('remarks', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='inspection.inspectionitemresponse')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inspection.inspectionreview')),
            ],
        ),
    ]
