# Generated by Django 4.2 on 2026-07-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0002_inspectionreview_inspectionitemreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionitemreview',
            name='critical_finding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspectionitemreview',
            name='rectification_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspectionitemreview',
            name='reviewed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inspectionitemreview',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('rework', 'Need Rectification')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspectionitemreview',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionitemreview',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterUniqueTogether(
            name='inspectionitemreview',
            unique_together={('review', 'response')},
        ),
    ]
