# Generated by Django 4.2 on 2026-07-28 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('property_type', models.CharField(choices=[('residential_apartment', 'Residential Apartment'), ('independent_villa', 'Independent Villa'), ('independent_house', 'Independent House'), ('row_house', 'Row House'), ('commercial_building', 'Commercial Building'), ('industrial_structure', 'Industrial Structure'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_template_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_template_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'master_templates',
                'ordering': ['-created_at'],
            },
        ),
    ]
