# Generated by Django 4.2 on 2026-07-28 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='template',
            table='templates',
        ),
    ]
