# Generated by Django 4.2 on 2026-07-28 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_alter_template_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='template',
            table='master_templates',
        ),
    ]
