# Generated by Django 4.2 on 2026-07-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionlibrary',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
