# Generated by Django 4.2.30 on 2026-07-08 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0006_alter_question_type'),
        ('response', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionreport',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspection_reports', to='questionnaires.template'),
        ),
    ]
