# Generated by Django 4.2.30 on 2026-07-08 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0002_alter_inspectionreport_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionreport',
            name='app_version',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='device_info',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='inspection_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='inspection_duration',
            field=models.IntegerField(blank=True, help_text='Duration in seconds', null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='inspection_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='submitted_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='total_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inspectionresponse',
            name='answered_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspectionresponse',
            name='is_na',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspectionresponse',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionresponse',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
